{% set name = "arraylake" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/arraylake-{{ version }}.tar.gz
  sha256: d34b3ff2228ddb22b4541d59f8fdd77db9bff572d884bd31752c5720daefc7c9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - arraylake = arraylake.cli.main:app
    - al = arraylake.cli.main:app

requirements:
  host:
    - python >=3.10,<3.13
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
    - pip
  run:
    - ruamel.yaml >=0.17,<1.0
    - python >=3.10,<3.13
    - aiobotocore >=2.4.0,<3.0.0
    - aioitertools >=0.11.0,<0.12.0
    - boto3 >=1.24.0,<2.0.0
    - botocore >=1.27.0,<2.0.0
    - click >=8.1.0,<9.0.0
    - donfig >=0.7,<1.0
    - email_validator >=2,<3
    - httpx >=0.23.0,<1.0
    - numpy >=1.23.0,<2.0.0
    - pydantic >=2.3.0,<3.0.0
    - python-dateutil >=2.8.0,<3.0.0
    - pyyaml >=6,<7.0
    - rich >=12.6,<14.0
    - ruamel.yaml >=0.17,<1.0
    - structlog >=24.1.0,<25.0.0
    - typer >=0.6.1,<1.0
    - uvloop <1.0,>=0.17  # [unix]
    - zarr >=2.14,<3.0
    - numcodecs !=0.12.0
    - __unix  # [unix]
    - __win   # [win]
    - cachetools >=5.3.2,<6.0.0
    - typing-extensions
    - fsspec >=2023.01.0
    - s3fs >=2023.01.0
    - gcsfs >=2023.01
    - sqlitedict >=2.1.0,<3.0.0
    - tenacity >=8.4.1,<9.0.0
    - humanize >=4.9.0,<5.0.0
  run_constrained:
    - cfgrib >=0.9,<1
    - python-eccodes >=1.6.1,<2
    - h5py >=3.7.0,<4.0.0
    - ipytree >=0.2.2,<1.0
    - kerchunk >=0.1,<1.0,!=0.2.1
    - tifffile >=2023.2.27
    - uvloop >=0.17,<1.0
    - xarray >=v2022.12.0
    - netcdf4 >=1.6.1,<1.7

test:
  imports:
    - arraylake
  commands:
    - pip check
    - arraylake --version
  requires:
    - pip

about:
  home: https://docs.earthmover.io
  summary: Python client for ArrayLake
  license: 'Unlicense'

extra:
  recipe-maintainers:
    - rabernat
    - jhamman
    - dcherian
    - monodeldiablo
